defaults:
  - _self_
  - model: base
  - stores: base
  - optimizer: base

general:
  num_classes: 10
  device: "cpu"
  project_name: "peekingduck"
  debug: true
  seed: 1992

hydra:
  run:
    dir: "outputs/${general.project_name}/${stores.unique_id}" # in sync with stores
