name: Deploy Mkdocs to GitHub Pages 
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt
      - run: mkdocs gh-deploy --force